# -*- coding: utf-8 -*-
"""lenet_&_Resnet_DL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jHtIfZ0vFpVqZYo6dTOjxj_Iief5g6nf
"""

from google.colab import drive
drive.mount('/content/drive')

pip install tensorflow

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np

import tensorflow as tf
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy #should research
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint #should research

from keras.layers import Convolution2D, MaxPooling2D
from keras.layers import Dense, Flatten
from keras.models import Sequential


import os

from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
import itertools
import shutil
import matplotlib.pyplot as plt
# %matplotlib inline

input_path = '/content/drive/MyDrive/LENET'
os.listdir(input_path)

import os

main_dir = '/content/drive/MyDrive/LENET/main_dir'

# Create main directories safely
os.makedirs(main_dir, exist_ok=True)

train_dir = os.path.join(main_dir, 'train_dir')
val_dir = os.path.join(main_dir, 'val_dir')
test_dir = os.path.join(main_dir, 'test_dir')

os.makedirs(train_dir, exist_ok=True)
os.makedirs(val_dir, exist_ok=True)
os.makedirs(test_dir, exist_ok=True)

# Class names
classes = ['nv', 'mel', 'bkl', 'bcc', 'akiec', 'vasc', 'df']

# Create class folders for train, val, test
for cls in classes:
    os.makedirs(os.path.join(train_dir, cls), exist_ok=True)
    os.makedirs(os.path.join(val_dir, cls), exist_ok=True)
    os.makedirs(os.path.join(test_dir, cls), exist_ok=True)

import os
df_data = pd.read_csv('/content/drive/MyDrive/LENET/HAM10000_metadata.csv')

df_data.head()

df = df_data.groupby('lesion_id').count()

df = df[df['image_id'] == 1]

df.reset_index(inplace=True) #should research

def identify_duplicates(x):

    unique_list = list(df['lesion_id'])

    if x in unique_list:
        return 'no_duplicates'
    else:
        return 'has_duplicates'

df_data['duplicates'] = df_data['lesion_id']

df_data['duplicates'] = df_data['duplicates'].apply(identify_duplicates)

df.shape

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

from sklearn.model_selection import KFold, StratifiedKFold

skf = StratifiedKFold(n_splits = 10,random_state = 7, shuffle = True)

df = df_data[df_data['duplicates'] == 'no_duplicates']

y = df['dx']
print(df.shape)

#_, df_val = train_test_split(df, test_size = 0.17, random_state=101, stratify=y)
#should research
df_train, df_test, y_train, y_test = train_test_split(df, y, test_size=0.3627, random_state=1)

df_test, df_val, y_test, y_val = train_test_split(df_test, y_test, test_size=0.5, random_state=1)
print(df_train.shape)
print(df_test.shape)
print(df_val.shape)

def identify_val_rows(x):

    val_list = list(df_val['image_id'])
    test_list = list(df_test['image_id'])

    if str(x) in val_list or str(x) in test_list:
        return 'val'
    else:
        return 'train'


df_data['train_or_val'] = df_data['image_id']

df_data['train_or_val'] = df_data['train_or_val'].apply(identify_val_rows)

df_train = df_data[df_data['train_or_val'] == 'train']

df_train

df_val

df_test

import os
import shutil
from tqdm import tqdm

#Ensure image_id is index (safe check)
if 'image_id' in df_data.columns:
    df_data.set_index('image_id', inplace=True)

#Load image folders (FAST using set)
folder_1 = set(os.listdir(os.path.join(input_path, 'HAM10000_images_part_1')))
folder_2 = set(os.listdir(os.path.join(input_path, 'HAM10000_images_part_2')))

#Create lists
train_list = list(df_train['image_id'])
val_list = list(df_val['image_id'])
test_list = list(df_test['image_id'])


#FUNCTION to copy images (avoids repeating code)
def copy_images(image_list, target_dir):

    for image in tqdm(image_list):

        file_name = image + '.jpg'

        #Get label safely
        try:
            label = df_data.loc[image, 'dx']
        except KeyError:
            continue  # skip if not found

        #Check in folder 1
        if file_name in folder_1:
            src = os.path.join(input_path, 'HAM10000_images_part_1', file_name)
            dst = os.path.join(target_dir, label, file_name)
            shutil.copy(src, dst)

        #Check in folder 2
        elif file_name in folder_2:
            src = os.path.join(input_path, 'HAM10000_images_part_2', file_name)
            dst = os.path.join(target_dir, label, file_name)
            shutil.copy(src, dst)


#Run copying
print("Copying TRAIN images...")
copy_images(train_list, train_dir)

print("Copying VALIDATION images...")
copy_images(val_list, val_dir)

print("Copying TEST images...")
copy_images(test_list, test_dir)

"""**Data Augumentataion**"""

class_list = ['mel', 'bkl','bcc','akiec','vasc','df']

for clas in class_list:
    aug_dir = 'aug_dir'
    os.mkdir(aug_dir)

    img_dir = os.path.join(aug_dir, 'img_dir')
    os.mkdir(img_dir)

    img_class = clas

    img_list = os.listdir(train_dir +"/"+ img_class)

    for fname in img_list:

        src = os.path.join(train_dir +"/" + img_class,fname)
#         dst = os.path.join(img_dir,fname)
        dst = img_dir

        shutil.copy(src, dst)

    path = aug_dir
    save_path = train_dir +"/" + img_class

    datagen = ImageDataGenerator(rotation_range=180,width_shift_range=0.1,height_shift_range=0.1,zoom_range=0.1,horizontal_flip=True,vertical_flip=True,fill_mode='nearest')
    batch_size = 50

    aug_datagen = datagen.flow_from_directory(path, save_to_dir = save_path, save_format='jpg',target_size=(224,224),batch_size=batch_size)

    num_aug_imgs_wanted = 6000
    num_files = len(os.listdir(img_dir))
    num_batches = int(np.ceil((num_aug_imgs_wanted - num_files)/batch_size))

    for i in range(0, num_batches):
        imgs, labels = next(aug_datagen) #should research

    shutil.rmtree('aug_dir')

num_train_samples = 8000
num_val_samples = 1000
num_test_samples = 1000
train_batch_size = 10
val_batch_size = 10
test_batch_size = 10
image_size = 28

train_steps = np.ceil(num_train_samples / train_batch_size)
val_steps = np.ceil(num_val_samples / val_batch_size)
test_steps = np.ceil(num_test_samples / test_batch_size)

train_dir

datagen = ImageDataGenerator(preprocessing_function = tf.keras.applications.mobilenet.preprocess_input)

train_batches = datagen.flow_from_directory(train_dir,target_size = (image_size, image_size), batch_size=train_batch_size)

val_batches = datagen.flow_from_directory(val_dir,target_size=(image_size, image_size), batch_size=val_batch_size)

test_batches = datagen.flow_from_directory(test_dir, target_size=(image_size, image_size), batch_size=1,shuffle=False)

model = Sequential()
model.add(Convolution2D(6, kernel_size=(5, 5), activation='relu', input_shape=(28, 28, 3)))
# model.summary()
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Convolution2D(16, kernel_size=(5, 5), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(120, activation='relu'))
model.add(Dense(84, activation='relu'))
model.add(Dense(7, activation='softmax'))

model.summary()

def get_model_name(k):
    return 'model_'+str(k)+'.h5'

idg = ImageDataGenerator(width_shift_range=0.1,
                         height_shift_range=0.1,
                         zoom_range=0.3,
                         fill_mode='nearest',
                         horizontal_flip = True,
                         rescale=1./255)

df.columns

from matplotlib import pyplot
from matplotlib import pyplot as plt
filters, biases = model.layers[0].get_weights()
# normalize filter values to 0-1 so we can visualize them
f_min, f_max = filters.min(), filters.max()
filters = (filters - f_min) / (f_max - f_min)
# plot first few filters
n_filters, ix = 5, 1
for i in range(n_filters):
	# get the filter
	f = filters[:, :, :, i]
	# plot each channel separately
	for j in range(3):
		# specify subplot and turn of axis
		ax = pyplot.subplot(n_filters, 3, ix)
		ax.set_xticks([])
		ax.set_yticks([])
		# plot filter channel in grayscale
		pyplot.imshow(f[:, :, j], cmap='gray')
		ix += 1
# show the figure
pyplot.show()

model.compile(loss='categorical_crossentropy', optimizer='rmsprop',metrics=["accuracy"])

hist = model.fit(train_batches, steps_per_epoch=int(train_steps), epochs=20, validation_data= val_batches, validation_steps=int(val_steps))

model.save("model.h5")

filters, biases = model.layers[0].get_weights()
# normalize filter values to 0-1 so we can visualize them
f_min, f_max = filters.min(), filters.max()
filters = (filters - f_min) / (f_max - f_min)
# plot first few filters
n_filters, ix = 5, 1
for i in range(n_filters):
	# get the filter
	f = filters[:, :, :, i]
	# plot each channel separately
	for j in range(3):
		# specify subplot and turn of axis
		ax = pyplot.subplot(n_filters, 3, ix)
		ax.set_xticks([])
		ax.set_yticks([])
		# plot filter channel in grayscale
		pyplot.imshow(f[:, :, j], cmap='gray')
		ix += 1
# show the figure
pyplot.show()

from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.applications.vgg16 import preprocess_input
from numpy import expand_dims

predictions = model.predict(test_batches, steps=1000, verbose=1)

print(predictions)

test_labels = test_batches.classes

test_labels

loss, acc = model.evaluate(test_batches, verbose=1)

acc

def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()
    plt.savefig('conf.png')

confusion_mat = confusion_matrix(test_labels, predictions.argmax(axis=1))

test_batches.class_indices

cm_plot_labels = ['akiec', 'bcc', 'bkl', 'df', 'mel','nv', 'vasc']

plot_confusion_matrix(confusion_mat, cm_plot_labels, title='Confusion Matrix')

"""ResNet"""

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms, models
from torch.utils.data import DataLoader
import os

train_dir = "/content/drive/MyDrive/LENET/main_dir/train_dir"
val_dir = "/content/drive/MyDrive/LENET/main_dir/val_dir"
test_dir = "/content/drive/MyDrive/LENET/main_dir/test_dir"

transform = transforms.Compose([
    transforms.Resize((224, 224)),  # ResNet needs 224x224
    transforms.ToTensor(),
    transforms.Normalize([0.5], [0.5])
])

train_dataset = datasets.ImageFolder(train_dir, transform=transform)
val_dataset = datasets.ImageFolder(val_dir, transform=transform)
test_dataset = datasets.ImageFolder(test_dir, transform=transform)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32)
test_loader = DataLoader(test_dataset, batch_size=32)

model = models.resnet18(pretrained=True)

# Modify final layer
num_classes = len(train_dataset.classes)
model.fc = nn.Linear(model.fc.in_features, num_classes)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

from tqdm import tqdm

epochs = 5

for epoch in range(epochs):
    model.train()
    running_loss = 0
    batch_size = 64
    correct = 0
    total = 0

    loop = tqdm(train_loader, desc=f"Epoch [{epoch+1}/{epochs}]", leave=True)

    for images, labels in loop:
        images, labels = images.to(device), labels.to(device)

        # Forward
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)

        # Backward
        loss.backward()
        optimizer.step()

        # Loss
        running_loss += loss.item()

        # Accuracy
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

        # Update progress bar
        loop.set_postfix(
            loss=running_loss / (loop.n + 1),
            acc=100 * correct / total
        )

    # Validation step
    model.eval()
    val_correct = 0
    val_total = 0

    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)

            _, predicted = torch.max(outputs, 1)
            val_total += labels.size(0)
            val_correct += (predicted == labels).sum().item()

    print(f"\nEpoch {epoch+1} Summary:")
    print(f"Train Loss: {running_loss:.4f}")
    print(f"Train Accuracy: {100 * correct / total:.2f}%")
    print(f"Validation Accuracy: {100 * val_correct / val_total:.2f}%\n")

model.eval()
test_correct = 0
test_total = 0

all_preds = []
all_labels = []

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = model(images)

        _, predicted = torch.max(outputs, 1)

        test_total += labels.size(0)
        test_correct += (predicted == labels).sum().item()

        all_preds.extend(predicted.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

print(f"Test Accuracy: {100 * test_correct / test_total:.2f}%")

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(all_labels, all_preds)

disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot(cmap='Blues')
plt.title("Confusion Matrix")
plt.show()

from sklearn.metrics import classification_report

print(classification_report(all_labels, all_preds))

torch.save(model.state_dict(), "/content/drive/MyDrive/LENET/resnet_model.pth")